-- =============================================
-- Author:		Nawfel HAMDI
-- Create date: 15/04/2025
-- Description:	Value Functions
-- Link : https://www.youtube.com/watch?v=Wvg4PjbMTO8
-- =============================================
