-- =============================================
-- Author:		Nawfel HAMDI
-- Create date: 10/05/2025
-- Description:	 NFORMATION_SCHEMA
-- =============================================

SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Number of TABLE_TYPE
SELECT T.TABLE_TYPE, COUNT(*) CountOfTableTypes
FROM INFORMATION_SCHEMA.TABLES AS T
GROUP BY T.TABLE_TYPE

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS AS T
WHERE T.TABLE_CATALOG = 'Compylo_SQL_InterviewQuestions'
AND T.TABLE_NAME = 'CutOff_S_MARKS'

SELECT T.CONSTRAINT_NAME, T.CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS T
WHERE T.TABLE_CATALOG = 'Compylo_SQL_InterviewQuestions'
AND T.TABLE_NAME = 'ComputedColumnTable_Query'

SELECT 
    rc.CONSTRAINT_NAME,
    actualTable.TABLE_NAME, 
    actualTable.COLUMN_NAME, 
    actualTable.ORDINAL_POSITION,
    rc.UNIQUE_CONSTRAINT_NAME,
    lookup.TABLE_NAME, 
    lookup.COLUMN_NAME, 
    lookup.ORDINAL_POSITION
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE actualTable
    ON actualTable.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE lookup
    ON lookup.CONSTRAINT_NAME = rc.UNIQUE_CONSTRAINT_NAME
    AND actualTable.ORDINAL_POSITION = lookup.ORDINAL_POSITION
WHERE actualTable.TABLE_NAME = 'TABLE NAME HERE';
